env:
  CIRRUS_CLONE_DEPTH: 3
  IGNORE_OSVERSION: yes
  MAKEFLAGS: '-j 2'

task:
  freebsd_instance:
    image_family: freebsd-$OSREL
  env:
    matrix:
      - OSREL: 11-4
      - OSREL: 12-2
      - OSREL: 13-0-snap
  script:
    - freebsd-version
    - pkg install -qy autoconf
    - touch .devel
    - cc --version
    - ./configure --prefix=/tmp
    - make CFLAGS=-Werror
    - ./tcpslice -h
    - make install
    - make releasetar
