env:
  CIRRUS_CLONE_DEPTH: 3
  IGNORE_OSVERSION: yes
  MAKEFLAGS: '-j 2'
  MATRIX_CC: 'clang gcc48 gcc10'

task:
  freebsd_instance:
    image_family: freebsd-$OSREL
  env:
    matrix:
      - OSREL: 11-4
      - OSREL: 12-2
      - OSREL: 13-0-snap
  script:
    - freebsd-version
    - pkg install -qy autoconf gcc48 gcc10
    - pkg install -qy bash git # for build_matrix.sh and build.sh
    - ./build_matrix.sh
