git:
  quiet: true
  depth: 3

os:
  - linux

dist: focal # Ubuntu 20.04

language: c

jobs:
  fast_finish: true
  include:
  - name: "arm64"
    arch: arm64
    if: branch == master
  - name: "ppc64le"
    arch: ppc64le
    if: branch == master
  - name: "s390x"
    arch: s390x
    if: branch == master
  allow_failures:
    - arch: ppc64le # Since 20 Feb 2021 often times out trying to boot.

env:
  global:
    - MAKEFLAGS='-j 2'

addons:
  apt:
    packages:
      - libpcap-dev
      - libnids-dev # Enables more code on it own.
      - libosip2-dev # Enables even more code when libnids-dev is installed.

before_install:
  - uname -a
  - date
  - if [ "$TRAVIS_OS_NAME" = linux ]; then apt list --installed 'lib*-dev'; fi

script:
  - ./build_matrix.sh
